### ISSUE TITLE
MySQL Installation Instruction on Ubuntu

### ISSUE THREAD

**Issue by u61** [HackYourFuture/databases#251]
MySQL installation on linux machines might be a struggle for students starting database module.
By Unmesh's request, I recorded a video about it. It might be useful to put link in the repo.

https://youtu.be/Y_LibBhOGOY

**Comment by NoerGitKat** [comment]
It's in there now! Thanks again Utku :)

**Comment by u61** [comment]
Don't forget others Noer 👍 

https://www.youtube.com/watch?v=8KpfpP32iro&t=13s
https://www.youtube.com/watch?v=tzC7vORso60&t=96s

I can also send videos directly to you if you want them to be exist in HYF's youtube channel.
