### ISSUE TITLE
Brew Package Manager installation step for MacOS is missing in Week1/README.md

### ISSUE THREAD

**Issue by u61** [HackYourFuture/databases#308]
For being able to install MySQL via brew in mac systems, users should install brew package manager first via this command:

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

This command can be added in https://github.com/HackYourFuture/databases/blob/master/Week1/README.md

**Comment by unmeshvrije** [comment]
You are right! Can you make a pull request with this change in Week1/README.md 
I will approve it
