### ISSUE TITLE
MySQL installation link in Week1/MAKEME.md can be changed

### ISSUE THREAD

**Issue by u61** [HackYourFuture/databases#309]
The link in the first line of Week1/MAKEME.md is redirecting you to MySQL Community Server download page. I noticed that some of the students downloaded MySQL from here, but couldn't install it because, this edition doesn't include any executable setup file(I noticed that for Windows systems). Link can be changed with this one which belongs to complete MySQL installer:

https://dev.mysql.com/downloads/installer/

**Comment by unmeshvrije** [comment]
Thanks for pointing that out. Can you make a Pull request with the change of link and I can approve it
