### ISSUE TITLE
Add link or description of prep-exercises in 'Homework Databases Week 2'

### ISSUE THREAD

**Issue by SergPerep** [HackYourFuture/databases#518]
[Homework Databases Week 2](https://github.com/HackYourFuture/databases/blob/master/Week2/MAKEME.md) has a section **2. Prep-exercises**. It tells a student to find `QA_PREP_EXERCISE.md`:
- Why not give a link to the file? Like 'Navigate to [QA_PREP_EXERCISE.md](https://github.com/HackYourFuture/databases/blob/master/Week2/QA_PREP_EXERCISE.md)'. Right now the student has to search the file themselves.
- Or better. Why not dump the content of QA_PREP_EXERCISE.md into the [Homework Databases Week 2 MAKEME.md](https://github.com/HackYourFuture/databases/blob/master/Week2/MAKEME.md)? `QA_PREP_EXERCISE.md` doesn't have that much content.

**Comment by robvk** [comment]
Done!
